version: "3.7"

services:

  #databases
  login-db:
    container_name: login-db
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./.volumes/login-db:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_PASSWORD=super_secure_password

  #frontends
  login-frontend:
    container_name: login-frontend
    build:
      context: ./
    restart: always
    expose:
      - "80"

  #backends
  login-backend:
    container_name: login-backend
    image: ghcr.io/gamify-it/login-backend:latest
    restart: always
    expose:
      - "80"
    depends_on:
      - login-db
    environment:
      - PORT=80
      - JWT_VALIDITY_DURATION=720h
      - JWT_KEY=SecretKEY
      - POSTGRES_URL=postgresql://postgres:super_secure_password@login-db:5432/

  # reverse-proxy
  reverse-proxy:
    container_name: reverse-proxy
    image: nginx
    restart: always
    depends_on:
      - login-backend
      - login-frontend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
