version: "3.7"

services:

  # databases
  setup:
    container_name: setup
    image: ghcr.io/gamify-it/test-data:feature-keycloak
    pull_policy: always
    restart: on-failure
    environment:
      POSTGRES_SETUP: >
        keycloak/default.sql

  keycloak-db:
    container_name: keycloak-db
    image: postgres:14-alpine
    restart: always
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=keycloak

  # login
  keycloak:
    container_name: keycloak
    expose:
      - "80"
    ports:
      - "8080:80"
    image: quay.io/keycloak/keycloak:19.0
    command:
      - "start-dev"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/postgres
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres

      KC_PROXY: edge
      KC_HOSTNAME: localhost
      KC_HOSTNAME_ADMIN: localhost
      KC_HTTP_RELATIVE_PATH: /keycloak
      KC_HTTP_PORT: 80

  # frontends
  landing-page:
    container_name: landing-page
    build: .
    expose:
      - "80"

  # reverse-proxy
  reverse-proxy:
    container_name: reverse-proxy
    image: nginx
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
